server:
  port: 80
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 145791255843-bbefnm7nvu2c17f2rta3kft4vs0hoacu.apps.googleusercontent.com
            clientSecret: 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
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_app
    password: 1227
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  main:
    lazy-initialization: true
jwt:
  secretKey: SupperKey
  expireTime: 864000000
